package com.houseman.domain.contract.dto

import com.houseman.domain.contract.PastContract
import java.time.LocalDate

data class PastContractResponse(
    val id: Long,
    val buildingId: Long,
    val buildingName: String,
    val roomId: Long,
    val roomNumber: String,
    val name: String,
    val phone: String,
    val moveIn: LocalDate,
    val moveOut: LocalDate,
    val expiry: LocalDate?,
    val deposit: Long,
    val rent: Long,
    val mgmt: Long?,
    val roomType: String?,
    val due: String?,
    val rentDay: Int?,
    val reason: String,
    val settlement: String,
    val settlementDate: LocalDate?,
    val cleanFee: Long?,
    val elecReading: Long?,
    val gasReading: Long?,
    val waterReading: Long?,
    val damageFee: Long?,
    val damageDesc: String?,
    val penalty7: Long?,
    val penaltyReason: String?,
    val daysInMonth: Int?,
    val usedDays: Int?,
    val startDay: Int?,
    val rentProRata: Long?,
    val mgmtProRata: Long?,
    val depositReturn: Long?,
    val totalDeduct: Long?,
    val finalRefund: Long?,
    val brokerageFee: Long?,
) {
    companion object {
        fun from(pc: PastContract): PastContractResponse = PastContractResponse(
            id = pc.id,
            buildingId = pc.building.id,
            buildingName = pc.building.name,
            roomId = pc.room.id,
            roomNumber = pc.room.roomNumber,
            name = pc.name,
            phone = pc.phone,
            moveIn = pc.moveIn,
            moveOut = pc.moveOut,
            expiry = pc.expiry,
            deposit = pc.deposit,
            rent = pc.rent,
            mgmt = pc.mgmt,
            roomType = pc.roomType,
            due = pc.due,
            rentDay = pc.rentDay,
            reason = pc.reason,
            settlement = pc.settlement,
            settlementDate = pc.settlementDate,
            cleanFee = pc.cleanFee,
            elecReading = pc.elecReading,
            gasReading = pc.gasReading,
            waterReading = pc.waterReading,
            damageFee = pc.damageFee,
            damageDesc = pc.damageDesc,
            penalty7 = pc.penalty7,
            penaltyReason = pc.penaltyReason,
            daysInMonth = pc.daysInMonth,
            usedDays = pc.usedDays,
            startDay = pc.startDay,
            rentProRata = pc.rentProRata,
            mgmtProRata = pc.mgmtProRata,
            depositReturn = pc.depositReturn,
            totalDeduct = pc.totalDeduct,
            finalRefund = pc.finalRefund,
            brokerageFee = pc.brokerageFee,
        )
    }
}

data class PastContractGroupResponse(
    val buildingName: String,
    val roomNumber: String,
    val records: List<PastContractResponse>,
)
