package com.houseman.domain.billing.dto

import com.houseman.domain.billing.SettlementMaster
import java.math.BigDecimal

data class SettlementMasterResponse(
    val id: Long,
    val buildingId: Long,
    val buildingName: String,
    val type: String,
    val feeType: String,
    val feeRate: BigDecimal,
    val feeAmount: Long?,
    val feeAmountIncludesVat: Boolean,
    val direction: String,
    val settlementDay: String,
    val periodType: String,
    val vat: Boolean,
    val vatMode: String?,
    val address: String,
    val ownerName: String?,
    val notes: String,
    val accountType: String?,
    val frequency: String?,
    val includeMgmt: Boolean?,
    val dualAccount: Boolean?,
    val moveoutOwnerBurden: Boolean?,
    val hasCommercial: Boolean?,
    val cashSplit: Boolean?,
    val feeVariable: Boolean?,
    val autoTransfer: Boolean?,
    val dualSection: Boolean?,
    val mgmtFeePerUnit: Long?,
    val dates: List<Any>?,
    val customPeriod: Map<String, Any>?,
    val subItems: List<Map<String, Any>>?,
    val costItems: List<Map<String, Any>>?,
    val hybridRules: List<Map<String, Any>>?,
    val elecCustomerMap: Map<String, Any>?,
    val gasCodeMap: Map<String, Any>?,
    val billingType: String?,
    val accounts: Map<String, Any>?,
    val abbr: String?,
) {
    companion object {
        fun from(entity: SettlementMaster): SettlementMasterResponse = SettlementMasterResponse(
            id = entity.id,
            buildingId = entity.building.id,
            buildingName = entity.buildingName,
            type = entity.type,
            feeType = entity.feeType,
            feeRate = entity.feeRate,
            feeAmount = entity.feeAmount,
            feeAmountIncludesVat = entity.feeAmountIncludesVat,
            direction = entity.direction,
            settlementDay = entity.settlementDay,
            periodType = entity.periodType,
            vat = entity.vat,
            vatMode = entity.vatMode,
            address = entity.address,
            ownerName = entity.ownerName,
            notes = entity.notes,
            accountType = entity.accountType,
            frequency = entity.frequency,
            includeMgmt = entity.includeMgmt,
            dualAccount = entity.dualAccount,
            moveoutOwnerBurden = entity.moveoutOwnerBurden,
            hasCommercial = entity.hasCommercial,
            cashSplit = entity.cashSplit,
            feeVariable = entity.feeVariable,
            autoTransfer = entity.autoTransfer,
            dualSection = entity.dualSection,
            mgmtFeePerUnit = entity.mgmtFeePerUnit,
            dates = entity.dates,
            customPeriod = entity.customPeriod,
            subItems = entity.subItems,
            costItems = entity.costItems,
            hybridRules = entity.hybridRules,
            elecCustomerMap = entity.elecCustomerMap,
            gasCodeMap = entity.gasCodeMap,
            billingType = entity.billingType,
            accounts = entity.accounts,
            abbr = entity.abbr,
        )
    }
}
